typography_spectrum: 0.20093836775049567
color:
  saturation: 0.8558672608342022
  brandStrength: 0.1830746240448207
  rhythmicContrast: 0.414958966197446
  brandColors:
    - '#FFF8E3'
    - '#CCCC9F'
    - '#33332D'
    - '#9FB4CC'
    - '#DB4105'
  lightness: 0.5829768774565309
layout_spectrum: 0.4935809881426394
author:
  name: ''
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/feb93c91-e0d0-4585-80bf-dca38ad46f8b.png
name: reckless pebbles
navigation:
  - name: Building Design in Australia
    id: a1706ce1-aabd-4ee7-9fa3-4cf2e6e0e21a
    type: content
  - name: Rav Kav Concept Design
    id: a46b16fa-701b-40d3-ac7a-1406b0a8fa68
    type: content
  - name: MetaKeyboard | The first AR Keyboard
    id: aa73c69d-1b2f-40a8-a9d4-ed87943d8b3d
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/14483813-8905-479e-af38-3a56eaaab8ed.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Mr. AR
description: Some projects I've been working on
