typography_spectrum: 0.20093836775049567
color:
  saturation: 0.8558672608342022
  brandStrength: 0.1830746240448207
  rhythmicContrast: 0.414958966197446
  brandColors:
    - '#FFF8E3'
    - '#CCCC9F'
    - '#33332D'
    - '#9FB4CC'
    - '#DB4105'
  lightness: 0.5829768774565309
layout_spectrum: 0.4935809881426394
author:
  name: ''
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/feb93c91-e0d0-4585-80bf-dca38ad46f8b.png
name: reckless pebbles
navigation:
  - name: Blog
    url: 'https://www.medium.com/@avrahamraskin'
    type: external
  - name: Portfolio
    id: 0d6e0ba0-16a8-4b40-986c-4cb40a361ab6
    type: content
  - name: Articles
    id: 0975a95b-2871-4f05-9f34-4a0c8c089c0f
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/14483813-8905-479e-af38-3a56eaaab8ed.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Side Projects
