typography_spectrum: 0.27864
color:
  brandColors:
    - '#FFF8E3'
    - '#CCCC9F'
    - '#33332D'
    - '#9FB4CC'
    - '#DB4105'
  brandStrength: 0.3125
  lightness: 0.5829768774565309
  saturation: 0.8558672608342022
  rhythmicContrast: 0.414958966197446
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.64357
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: ''
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/feb93c91-e0d0-4585-80bf-dca38ad46f8b.png
name: reckless pebbles
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: the Person
    id: 8f204118-33fb-4264-bfc1-0143cc1cda56
    type: content
  - name: Rav Kav Concept Design
    id: a46b16fa-701b-40d3-ac7a-1406b0a8fa68
    type: content
  - name: HakAR | AR Music Player​
    id: a3232c9c-8213-4fa6-9fa0-e5c27a0da070
    type: content
  - name: Building Design in Australia
    id: a1706ce1-aabd-4ee7-9fa3-4cf2e6e0e21a
    type: content
  - name: Follow the Leader | Social Robots
    id: 54f2ebac-40dc-45b9-a8bd-7cbe2d78c7cb
    type: content
  - name: ReticleGesture | Control your AR world
    id: 81de3bbb-54bd-463a-ba5d-3c42ddb0755d
    type: content
  - name: MetaKeyboard | The first AR Keyboard
    id: aa73c69d-1b2f-40a8-a9d4-ed87943d8b3d
    type: content
  - name: MetaSky | The Weather Naturally​
    id: 5e78a7c7-6779-4436-a003-cbb32a4fd84f
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/14483813-8905-479e-af38-3a56eaaab8ed.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Mr. AR
description: Some projects I've been working on
purpose: []
