typography_spectrum: 0.9416031632572412
color:
  brandColors:
    - '#FFF8E3'
    - '#CCCC9F'
    - '#33332D'
    - '#9FB4CC'
    - '#DB4105'
  brandStrength: 0.3125
  lightness: 0.5829768774565309
  saturation: 0.8558672608342022
  rhythmicContrast: 0.414958966197446
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5623886079993099
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: ''
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/feb93c91-e0d0-4585-80bf-dca38ad46f8b.png
name: reckless pebbles
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Projects
    id: fff899ea-54bb-4a68-910e-93a6036efbda
    type: content
  - name: Some articles
    url: 'https://medium.com/@avrahamraskin'
    type: external
  - name: UIs Gallery
    id: 036767f6-3cb9-48b9-b45b-d8265e9da54e
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/14483813-8905-479e-af38-3a56eaaab8ed.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Mr. AR
description: Augmented Reality Conceptualiser
purpose: []
